name: Notice Frontend CI (Develop)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

# Environment variables
env:
  NODE_VERSION: "16"  

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm" 

      
      - name: Install dependencies
        run: npm ci  
        working-directory: ./frontend  

      
      - name: Lint frontend
        run: npm run lint || echo "Linting not configured, skipping..."
        working-directory: ./frontend  
        continue-on-error: true  

      
      - name: Test frontend
        run: npm test || echo "Tests not configured, skipping..."
        working-directory: ./frontend  
        env:
          CI: true  


      - name: Build frontend
        run: npm run build
        working-directory: ./frontend  